[general]
import = [
	"~/.config/alacritty/keybindings.toml",
	"~/.config/alacritty/themes/themes/ayu_mirage.toml"
]

[selection]
save_to_clipboard = true

[font]
size = 17
normal.family = "Hack Nerd Font"

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Windowed"
padding.x = 10
padding.y = 10
position.x = 1200
position.y = 900
dimensions.columns = 140
dimensions.lines = 30
decorations = "Buttonless"
opacity = 0.90
blur = true
