[general]
import = [
	"~/.config/alacritty/keybindings.toml",
	"~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[selection]
save_to_clipboard = true

[font]
size = 17

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
dimensions.columns = 140
dimensions.lines = 30
decorations = "Full"
opacity = 0.92
