[keyboard]
bindings = [
	{ key = "Space", mods = "Option", action = "ToggleViMode" },
	{ key = "C", mods = "Command", action = "Copy" },
	{ key = "P", mods = "Command", action = "Paste" },
 	{ key = "J", mods = "Alt", chars = "\u001bB" },
  	{ key = "K", mods = "Alt", chars = "\u001bF" },
	{ key = "H", mods = "Alt", chars = "\u0001" },
	{ key = "L", mods = "Alt", chars = "\u0005" },
]
