[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
position.x = 700
position.y = 200

decorations = "Full"
opacity = 0.92

[window.dimensions]
columns = 133
lines = 30

[font]
size = 20.0

[colors.primary]
background = '0x282828'
foreground = '0xd4be98'

[colors.normal]
black = '0x3c3836'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'

[colors.bright]
black = '0x3c3836'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'
